# Common configuration for all services
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
logging:
  level:
    org.springframework.cloud: DEBUG
